version: 2.0.{build}
image: Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov
build_script:
- cd src && dotnet build -c Release && cd ..
test_script:
- cd tests && dotnet add package Appveyor.TestLogger --version 2.0.0 && dotnet restore && dotnet test --test-adapter-path:. --logger:Appveyor
- OpenCover.Console.exe -register:user -target:"dotnet.exe" -targetargs:test -filter:"+[GlitchedPolygons.Services.Cryptography.Symmetric*]* -[GlitchedPolygons.Services.Cryptography.Symmetric.Tests*]*" -output:".\coverage.xml" -oldstyle
- codecov -f "coverage.xml"